spring:
  application:
    # Application name
    name: stellarmind-server

  main:
    # Disable Spring banner during startup
    banner-mode: off
    # Uncomment if you want to disable the web server (for STDIO transport)
    # web-application-type: none

  datasource:
    # PostgreSQL connection details
    url: jdbc:postgresql://localhost:5439/nexusconnect
    username: postgres
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    
  nexusconnect:
    auth:
      token: ${LWM2M_AUTH_TOKEN:}

  jpa:
    # Custom dialect for PGVector
    database-platform:
    hibernate:
      ddl-auto: update   # Auto-update schema (use cautiously in prod)
    show-sql: true       # Show SQL queries in logs

  mcp:
    server:
      # MCP server metadata
      name: nexusconnect-mcp-server
      version: 0.0.1
      # type: ASYNC   # Uncomment if server type should be ASYNC


logging:
  level:
    # Enable detailed logging for MCP integration
    org:
      springframework:
        ai:
          mcp: TRACE

management:
  endpoints:
    web:
      exposure:
        include: beans,health,info,env,conditions,configprops,loggers
  endpoint:
    health:
      show-details: when_authorized
  # optional: separate port for actuator so you donâ€™t expose it with your app
  server:
    port: 8082
